import os
import re
from pathlib import Path
from urllib.parse import urlparse

from pydub import AudioSegment
import yt_dlp


DOWNLOAD_DIR = Path(__file__).resolve().parent.parent / "downloades"
DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)


def _safe_filename(name: str) -> str:
    """Make a YouTube title safe for Windows/Linux filenames."""
    name = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", name)
    name = re.sub(r"\s+", " ", name).strip().rstrip(".")
    return name[:180] or "youtube_audio"


def _is_youtube_url(url: str) -> bool:
    host = urlparse(url).netloc.lower()
    return "youtube.com" in host or "youtu.be" in host


def download_youtube_audio(url: str) -> str:
    """Download YouTube audio and convert it to WAV."""
    output_template = str(DOWNLOAD_DIR / "%(title)s.%(ext)s")

    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": output_template,
        "noplaylist": True,
        "quiet": True,
        "no_warnings": True,
        "restrictfilenames": True,
        "postprocessors": [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": "wav",
                "preferredquality": "192",
            }
        ],
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            downloaded = Path(ydl.prepare_filename(info))

        wav_path = downloaded.with_suffix(".wav")

        if wav_path.exists():
            return str(wav_path)

        # Fallback: find the WAV generated by the postprocessor.
        matches = sorted(
            DOWNLOAD_DIR.glob(f"{_safe_filename(info.get('title', ''))}*.wav")
        )
        if matches:
            return str(matches[-1])

        raise FileNotFoundError(
            f"YouTube audio was downloaded but WAV output was not found: {wav_path}"
        )

    except Exception as exc:
        raise RuntimeError(
            "Unable to download audio from YouTube. "
            "The video may require authentication, be age/region restricted, "
            "or YouTube may have rejected the request. "
            f"Original error: {exc}"
        ) from exc


def convert_to_wav(input_path: str) -> str:
    """Convert any audio/video file to mono 16 kHz WAV."""
    if not os.path.isfile(input_path):
        raise FileNotFoundError(f"Input file not found: {input_path}")

    output_path = os.path.splitext(input_path)[0] + "_converted.wav"

    audio = AudioSegment.from_file(input_path)
    audio = audio.set_channels(1).set_frame_rate(16000)
    audio.export(output_path, format="wav")

    return output_path


def chunk_audio(wav_path: str, chunk_minutes: int = 10) -> list:
    """Split a WAV file into chunks for transcription."""
    audio = AudioSegment.from_wav(wav_path)
    chunk_ms = chunk_minutes * 60 * 1000

    chunks = []

    for i, start in enumerate(range(0, len(audio), chunk_ms)):
        chunk = audio[start:start + chunk_ms]
        chunk_path = f"{wav_path}_chunk_{i}.wav"
        chunk.export(chunk_path, format="wav")
        chunks.append(chunk_path)

    return chunks


def process_input(source: str) -> list:
    """Download/convert the input and return transcription-ready chunks."""
    source = source.strip()

    if not source:
        raise ValueError("Input source cannot be empty.")

    if source.startswith(("http://", "https://")):
        if _is_youtube_url(source):
            print("Detected YouTube URL. Downloading audio...")
            wav_path = download_youtube_audio(source)
        else:
            raise ValueError("Only YouTube URLs are supported for URL input.")
    else:
        print("Detected local file. Converting to WAV...")
        wav_path = convert_to_wav(source)

    print("Chunking audio...")
    chunks = chunk_audio(wav_path)
    print(f"Audio ready — {len(chunks)} chunk(s) created.")

    return chunks
